---
allowed:
  - apache-2.0
  - bsd-3-clause
  - mit
  - mpl-2.0

cache_path: .github/licenses/

source_path: cmd/*

# ignored:
#   go:
#     - github.com/percona-platform/**/*

reviewed:
  go:
    - github.com/golang-migrate/migrate/v4
    - github.com/golang-migrate/migrate/v4/database
    - github.com/golang-migrate/migrate/v4/database/postgres
    - github.com/golang-migrate/migrate/v4/internal/url
    - github.com/golang-migrate/migrate/v4/source
